---
- name: Update en webservers opzetten met een website van github
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  pre_tasks:

    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: Distribution version
      debug: msg="{{ ansible_distribution_version}}"
    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"

    - name: installeer updates op een RedHat Server
      tags: always
      ansible.builtin.dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Rocky"

    - name: installeer updates op een Ubuntu Server
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

  tasks:
    - name: nmap installeren op al onze servers.
      ansible.builtin.package:
        name:
          - nmap
